"""add_meetings_and_participants

Revision ID: 1e8f18a49488
Revises: 4d069317db2d
Create Date: 2026-06-28 17:28:23.493671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8f18a49488'
down_revision: Union[str, None] = '4d069317db2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'live', 'ended', 'cancelled', name='meeting_status_enum', native_enum=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at', name='ck_meeting_ended_after_started'),
    sa.CheckConstraint('max_participants > 0', name='ck_meeting_max_participants_positive'),
    sa.CheckConstraint('started_at IS NULL OR scheduled_at IS NULL OR started_at >= scheduled_at', name='ck_meeting_started_after_scheduled'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meetings_created_at', 'meetings', ['created_at'], unique=False)
    op.create_index('ix_meetings_host_id', 'meetings', ['host_id'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_code'), 'meetings', ['meeting_code'], unique=True)
    op.create_index('ix_meetings_scheduled_at', 'meetings', ['scheduled_at'], unique=False)
    op.create_index('ix_meetings_status', 'meetings', ['status'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('host', 'cohost', 'attendee', name='participant_role_enum', native_enum=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('is_video_off', sa.Boolean(), nullable=False),
    sa.Column('is_screen_sharing', sa.Boolean(), nullable=False),
    sa.CheckConstraint('left_at IS NULL OR left_at >= joined_at', name='ck_participant_left_after_joined'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_participant_meeting_user')
    )
    op.create_index('ix_participants_meeting_id', 'participants', ['meeting_id'], unique=False)
    op.create_index('ix_participants_user_id', 'participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_participants_user_id', table_name='participants')
    op.drop_index('ix_participants_meeting_id', table_name='participants')
    op.drop_table('participants')
    op.drop_index('ix_meetings_status', table_name='meetings')
    op.drop_index('ix_meetings_scheduled_at', table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_code'), table_name='meetings')
    op.drop_index('ix_meetings_host_id', table_name='meetings')
    op.drop_index('ix_meetings_created_at', table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
